### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by ahmgeek** [activeadmin-plugins/active_admin_import#100]
i am doing authorization with `strongbolt` [Here](https://github.com/AnalyticsMediaGroup/strongbolt).
the way of authorization is working for models not requests, so I have to givestrong bolt, the Model that will have some authorization to get it work, [Here](https://github.com/AnalyticsMediaGroup/strongbolt_example/blob/master/config/initializers/strongbolt.rb#L44)
and if there's a controller that I shouldn't authorize in like registration and sessions,  I should put it [Here](https://github.com/AnalyticsMediaGroup/strongbolt_example/blob/master/config/initializers/strongbolt.rb#L27)
so, with that said, Strong bolt give me a `can?` method, but only with the usual ReSTful actions `create, find, update, delete`
I couldn't get the gem work in my case, so any hints ?

**Comment by Fivell** [comment]
@ahmgeek , looks like you should implement custom authorization adapter for activeadmin to make it work, Manual can be found here http://activeadmin.info/docs/13-authorization-adapter.html
