### ISSUE TITLE
Add values to befor_import

### ISSUE THREAD

**Issue by ahmgeek** [activeadmin-plugins/active_admin_import#105]
if I want to insert to values on the fly while importing rows.
i.e I want to add to more columns but without the need to specify them on the csv file, one of the values is `uid` column which is the same user's email, so while import I want to create for every row, another `uid` that get's the email value from csv's email header, and `provider`, which is just a string `email`.

**Comment by Fivell** [comment]
@ahmgeek , take a look https://github.com/activeadmin-plugins/active_admin_import/issues/83 is it suitable for you?

**Comment by Fivell** [comment]
Also you can override headers on  template_object  level , and use custom code like in wiki example https://github.com/activeadmin-plugins/active_admin_import/wiki/change-columns-on-the-fly-by-association

**Comment by Fivell** [comment]
closing due inactivity

**Comment by ahmgeek** [comment]
I am Soooooooorry :cry: I forget to update you. I manage to do it #83 is suitable. Thanks.
here's a :kiss: just for your beard.
