### ISSUE TITLE
Postgres text array import

### ISSUE THREAD

**Issue by singfoom** [activeadmin-plugins/active_admin_import#115]
I've been trying with no success to upload an attribute that is being stored in Postgres as a text type, with array true.

The schema line for that attribute: `t.text  "verification_codes", default: [], array: true`

When creating the model via seeds or the console, the following creates the attribute as expected:
`:verification_codes => ["social_full", "birth_date"],`

I've tried many variations in the CSV, with the array brackets, without them, one double quote enclosed string.  There is no error and the object saves with the proper data with the exception of this attribute, which is input in the SQL as `'{}'`.  I didn't see any examples listing this and don't see anything in the code for this specific case.  

Please let me know if I'm going about this wrong or if there's a clear problem from the code above.  Thanks!

**Comment by Fivell** [comment]
@singfoom , not sure if it is supported by ```activerecord-import``` gem

**Comment by singfoom** [comment]
@Fivell Thanks, I'll close this issue out and prove out whether it's supported directly with `activerecord-import`
