### ISSUE TITLE
Is there a way to return error messages?

### ISSUE THREAD

**Issue by stonehz** [activeadmin-plugins/active_admin_import#12]
Apologies for posting a question here.. couldn't find a google group.
I'm trying to add some "user-friendly" features to the bulk import process and I was wondering if we can return helpful messages back to the user.. 
e.g. CSV line that the import failed, Validation Messages that stoped the process, etc.

**Comment by tdutreui** [comment]
Hi @Fivell 
I tried to use the code you provided on your comment, but it fails. There is a character escaping added everytime I call `@importer.headers` : 
```
@importer.headers
=> {"[\"title\", \"title\"]"=>"[\"title\",_\"title\"]", "[\"description\", \"description\"]"=>"[\"description\",_\"description\"]", ...}
```

Note : it works if I do the same inside the after_batch_import proc
I'm using version 2.5.1

**Comment by Fivell** [comment]
@tdutreui feel free to create PR

**Comment by Nishan983** [comment]
Hi @Fivell. I am a newbie to rails and active admin. I tried using the above code with slight modification to show error messages. But I am getting an error message for flash.  Could you please help me?

error: undefined local variable or method for flash.
