### ISSUE TITLE
Import only specific columns

### ISSUE THREAD

**Issue by codehugger** [activeadmin-plugins/active_admin_import#124]
I have a CSV file that the client wishes to upload with dozens of columns but I only need two of them. Is there a way to isolate the columns I want to import?

What I currently have now is this

```ruby
  active_admin_import validate: true,
                                     template_object: ActiveAdminImport::Model.new(
                                       csv_headers: ['SERIAL', 'NAME']
                                     ),
                                     headers_rewrites: { :'SERIAL' => :serial_number, :'NAME' => :name }
```

 ... which does not seem to work and I get this error in the ActiveAdmin UI

```
Failed to import 2733 products: ; ; ; ;
```

**Comment by Fivell** [comment]
@codehugger ,  you can use callback in importer to modify csv_lines just before it pass to activerecord-import. 

https://github.com/activeadmin-plugins/active_admin_import/blob/v3.0.0.pre/lib/active_admin_import/importer.rb#L103

**Comment by codehugger** [comment]
The code below works :) Thanks!

```ruby
  active_admin_import validate: true,
    before_batch_import: proc { |import|
      import.headers = { 'SERIAL' => 'serial_number', 'NAME' => 'name' }
      import.csv_lines = import.csv_lines.map { |l| [l[0], l[2]] }
    }
```

A nice to have would be to not have to rely on a certain column order in the file. Is there a way to get the values for csv_lines using the 'serial_number' and 'name' keys instead of 0 and 2 array indexes?

**Comment by Fivell** [comment]
@codehugger , you can capture position of csv column and then collect using this positions.
Example https://github.com/activeadmin-plugins/active_admin_import/blob/6eb70427497f1b8350cd2882a1e03121d24d2fca/lib/active_admin_import/importer.rb#L64
