### ISSUE TITLE
Passing params to import

### ISSUE THREAD

**Issue by Jamevid** [activeadmin-plugins/active_admin_import#130]
How about passing params to the import? So the web interface could hook up with the import. 

How about something like this:

```
# importer.rb
   # add attr_reader
    attr_reader :params

   # pass params:
    def initialize(resource, model, options, params)
      @params = params
```

```
# dls.rb 
    # pass params:
     @importer = Importer.new(options[:resource_class], @active_admin_import_model, options, params)
```

Just an idea.

**Comment by Fivell** [comment]
@Jamevid , it is already done
take a look https://github.com/activeadmin-plugins/active_admin_import/blob/d00758ae1e46ae44fd68ab217db66848428ce852/lib/active_admin_import/dsl.rb#L79

**Comment by Fivell** [comment]
@Jamevid , so you can access params using model.
https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/importer.rb#L5

**Comment by Fivell** [comment]
I opened access to wiki so everyone  can contribute now

**Comment by Jamevid** [comment]
Thanks for super fast answer ! 👍

**Comment by Jamevid** [comment]
ok, so if I wanna pass url params (or any options input by user) into the import I could  add a field in the form.

but there are a fixed set of fields as [default_attributes](https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/model.rb#L57 ) 

The [model](https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/options.rb#L28) is passed to view without possibility to override?

Sorry if I missed something.
