### ISSUE TITLE
Using tab as delimiter results in "Error: undefined method"

### ISSUE THREAD

**Issue by yaneeka** [activeadmin-plugins/active_admin_import#132]
When I set `csv_options: { col_sep: "\t" }` and use a file with tabs, I get an error such as "Error: undefined method `location_name_=' for #<TmpItemImport:0x007ff315d29be0> Did you mean? location=", where location and name are individual columns. Any idea what the issue might be?

**Comment by Fivell** [comment]
@yaneeka , please add full backtrace to your issue

**Comment by yaneeka** [comment]
Apologies, can you tell me where to find this? The output I listed above is what shows up in both the rails server output and on the active admin page.

**Comment by Fivell** [comment]
@yaneeka , do you see sort of this ? <img width="1436" alt="screen shot 2016-03-09 at 9 35 48 pm" src="https://cloud.githubusercontent.com/assets/6212082/13632666/f277ac5a-e63e-11e5-8874-6e43ec5eea6d.png">

**Comment by yaneeka** [comment]
@Fivell:
![screen shot 2017-03-16 at 11 49 30 pm](https://cloud.githubusercontent.com/assets/1578074/24032066/56a1d000-0aa3-11e7-8600-e43a3879fae9.png)

**Comment by Fivell** [comment]
@yaneeka  , I will be able to check this on weekend, if this problem is about tab delimiter.

**Comment by yaneeka** [comment]
@Fivell, thanks, appreciate it.

**Comment by Fivell** [comment]
@yaneeka , added feature test and fixed in master
