### ISSUE TITLE
Doesn't see file

### ISSUE THREAD

**Issue by bhgames** [activeadmin-plugins/active_admin_import#138]
I have this:

UPDATE: I am on Rails 5.0.2 with AA 1.0.0.pre5

`  active_admin_import validate: true, batch_transaction: true, batch_size: 100, before_import: :before_import_check
`

And when I attach a file and doimport, I get this:

https://screencast.com/t/t37k88jGy

This is using 3.0.0.pre as recommended in the read me.

The backend received this:

Started POST "/admin/jobs/do_import" for ::1 at 2017-04-20 10:59:32 -0500
  ActiveRecord::SchemaMigration Load (0.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Admin::JobsController#do_import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4xnvXwT2FgUiPF83hG35SoUxrW126Xm2pbLDycHDvSNVlpJYz46Ac0/B3ahyaIt6Cc9mmlX9iWwkgvphYLF4/g==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007f915ec01ab0 @tempfile=#<Tempfile:/var/folders/3j/2wcv7bl925l8s496d7st54540000gn/T/RackMultipart20170420-37614-1jjeds5.csv>, @original_filename="healthCareJobs.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"healthCareJobs.csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}
Geokit is using the domain: localhost
  AdminUser Load (1.6ms)  SELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Rendering /Users/arkavon/.rvm/gems/ruby-2.3.0@meddery/gems/active_admin_import-2.1.2/app/views/admin/import.html.erb within layouts/active_admin
DEPRECATION WARNING: input_class is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.input_class_finder instead (upgrade guide on wiki: http://bit.ly/1F9QtKc )) (called from input at /Users/arkavon/.rvm/gems/ruby-2.3.0@meddery/gems/formtastic-3.1.5/lib/formtastic/helpers/input_helper.rb:240)
DEPRECATION WARNING: action_class is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.action_class_finder instead (upgrade guide on wiki: http://bit.ly/1F9QtKc )) (called from action at /Users/arkavon/.rvm/gems/ruby-2.3.0@meddery/gems/formtastic-3.1.5/lib/formtastic/helpers/action_helper.rb:85)
  Rendered /Users/arkavon/.rvm/gems/ruby-2.3.0@meddery/gems/active_admin_import-2.1.2/app/views/admin/import.html.erb within layouts/active_admin (29.2ms)
Completed 200 OK in 614ms (Views: 545.6ms | ActiveRecord: 13.6ms)

Not sure where to go here.

**Comment by Fivell** [comment]
@bhgames , can you try master branch, refs https://github.com/activeadmin-plugins/active_admin_import/issues/91

**Comment by bhgames** [comment]
@Fivell I actually did that because I figured gem was out of date, and got a different error, but I don't remember the exact specifics. Something about an unknown attribute called source, I think. Because I was on a short timeline, I tore out the gem and built my own custom button action using ActiveAdmin, and that worked. Sorry I can't be of more assistance! You can probably close this since I can't reproduce it easily anymore.
