### ISSUE TITLE
We need a CHANGELOG

### ISSUE THREAD

**Issue by WaKeMaTTa** [activeadmin-plugins/active_admin_import#140]
Hello!

Can we add a *CHANGELOG.md*. Is very useful.

Thanks.

**Comment by workgena** [comment]
Agree, it is good practice. Meanwhile take a look at [Releases](https://github.com/activeadmin-plugins/active_admin_import/releases). We are trying to write what changed there.

**Comment by workgena** [comment]
Now we have [CHANGELOG.md](https://github.com/activeadmin-plugins/active_admin_import/blob/master/CHANGELOG.md)
