### ISSUE TITLE
How to access current_admin_user in before_batch_import?

### ISSUE THREAD

**Issue by mikefab** [activeadmin-plugins/active_admin_import#142]

**Comment by mikefab** [comment]
How can I attach the identity of the logged in user to the CSV I'm importing?

**Comment by Fivell** [comment]
@mikefab  https://github.com/activeadmin-plugins/active_admin_import/issues/88#issuecomment-192325909

**Comment by mikefab** [comment]
Wasn't able to follow that. 
In app/admin/schools.rb
ActiveAdmin.register School do
  before_filter only: [:do_import] do
  ...
results in: undefined method `before_filter' for #<ActiveAdmin::ResourceDSL:0x007fd297cb4ac8>

https://github.com/unicef/project-connect/blob/master/app/admin/schools.rb
Still need guidance.

**Comment by Fivell** [comment]
@mikefab  looks like before_action should be used instead for rails 5.1

**Comment by mikefab** [comment]
Solved. Thank you, Fivell!
