### ISSUE TITLE
Unable to deploy with capistrano

### ISSUE THREAD

**Issue by KONSTRUKTEUR** [activeadmin-plugins/active_admin_import#147]
I was trying to deploy an application to production with capistrano and the active_admin_import-x.x.x.gemspec threw an error on RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile.

I was able to solve it by editing the gemspec in production.

The file was:

    `# -*- encoding: utf-8 -*-

    Gem::Specification.new do |s|
      s.name = %q{active_admin_import}
      s.version = "2.0.1"

      s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
      s.authors = ["Igor Fedoronchuk"]
      s.date = %q{2013-09-11}
      s.description = %q{The most efficient way to import for Active Admin}
      s.email = ["fedoronchuk@gmail.com"]
      s.files = [".gitignore", "Gemfile", "LICENSE", "README.md", "Rakefile", "active_admin_import.gemspec", "app/views/admin/import.html.erb", "lib/active_admin_import.rb", "lib/active_admin_import/dsl.rb", "lib/active_admin_import/engine.rb", "lib/active_admin_import/importer.rb$
      s.homepage = %q{http://github.com/Fivell/active_admin_import}
      s.require_paths = ["lib"]
      s.rubygems_version = %q{1.3.7}
      s.summary = %q{ActiveAdmin import based on activerecord-import gem.}
    
      if s.respond_to? :specification_version then
        current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
        s.specification_version = 3

        if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
          s.add_runtime_dependency(%q<activerecord-import>, ["#<YAML::Syck::DefaultKey:0xf5f53c00> 0.3.0"])
        else
          s.add_dependency(%q<activerecord-import>, ["#<YAML::Syck::DefaultKey:0xf5f53c00> 0.3.0"])
        end
      else
        s.add_dependency(%q<activerecord-import>, ["#<YAML::Syck::DefaultKey:0xf5f53c00> 0.3.0"])
      end
    end`

After deleting `#<YAML::Syck::DefaultKey:0xf5f53c00> ` in the dependency declaration everything passed. When I checked the git the relative file does not have this section.

**Comment by Fivell** [comment]
seems rubygems issue, try to update rubygems

**Comment by Fivell** [comment]
closing as stale
