### ISSUE TITLE
Why version lock?

### ISSUE THREAD

**Issue by pankopiotr** [activeadmin-plugins/active_admin_import#151]
Is there a particular reason that this gem uses a year old version of `activerecord-import`?

Could you unlock version dependency or simply use newest version available?
There are few important issues that were fixed in recent versions of that gem.

**Comment by Fivell** [comment]
@keoghpe  yes u're right

**Comment by tatethurston** [comment]
> For activerecord-import < 0.18.0, if your ActiveRecord model validates the uniqueness of the column(s) used to determine whether a row conflicts with others, you should add validate: false to your import call, as running validation will filter out the row and prevent it from being updated.

https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update
