### ISSUE TITLE
Can't import Devise users

### ISSUE THREAD

**Issue by joshuaswilcox** [activeadmin-plugins/active_admin_import#16]
I can't seem to import users that are created through Devise.  I get an error
    Missing column for value <password> at index 3
which makes  sense since "password" isn't an actual field its "encrypted_password", but I am providing a default password for these users that I am importing which they are required to change after the import.  Is there anyway around this?

**Comment by andymilk** [comment]
@joshuaswilcox do you have the full import block for this?  I'm having a similar problem, but getting this error:  Error: Missing column for value <password> at index 2

**Comment by joshuaswilcox** [comment]
sure
```ruby
  active_admin_import :validate => false,
                            :before_batch_import => proc { |import|
                              import.csv_lines[0][3] = User.new(:password => import.csv_lines[0][3]).encrypted_password
                            },
                            :template_object => ActiveAdminImport::Model.new(
                                :hint => "file will be imported with such header format: 'first_name','last_name','email','password', 'team_id', 'age', 'gender'"
                            ),
                            :timestamps=> true,
                            :batch_size => 1000
```

**Comment by asecondwill** [comment]
Coping that block, I still get the error: 

"Missing column for value <password> at index 3"

my csv: 

first_name,last_name,email,password,password_confirmation

```` Bob,Smith,user@example.com,123456789,123456789 ````


Any clues?

**Comment by asecondwill** [comment]
@joshuaswilcox  - would you mind explaining what's happening here? why would we need to encrypt the password? why not the password_confirmation? what does the missing  column error mean?

**Comment by asecondwill** [comment]
I had a bit of trouble with this till the penny dropped to change the header to encrypted_password.

so 

first_name,last_name,email,encrypted_password
joe,blogs,user@example.com,12345678

````

  active_admin_import :validate => false,
                            :before_batch_import => proc { |import|
                             # binding.pry                              
                              import.csv_lines[0][3] = User.new(:password => import.csv_lines[0][3]).encrypted_password
                            },
                            after_batch_import: ->(importer) {
                             #the same
                            # binding.pry
                            },
                            :template_object => ActiveAdminImport::Model.new(
                                :hint => "file will be imported with the header format: 'first_name','last_name','email','password'"
                            ),
                            :timestamps=> true,
                            :batch_size => 1000 
````

**Comment by kyreeves** [comment]
@asecondwill @joshuaswilcox 

How would you do this if you had multiple attributes that were encrypted? I can't seem to figure it out.

**Comment by kyreeves** [comment]
@Fivell do you have any suggestions?

**Comment by Fivell** [comment]
@kyreeves , there is an example how to change data on the fly https://github.com/activeadmin-plugins/active_admin_import/wiki/change-columns-on-the-fly-by-association
