### ISSUE TITLE
Wrong count in notification after successful import

### ISSUE THREAD

**Issue by rafaltrojanowski** [activeadmin-plugins/active_admin_import#166]
I am getting "Successfully imported 6 things" while there are 5 records. I guess we count rows (CSV contains header).

**Comment by Fivell** [comment]
no its not, they are cuted from the beginning 
https://github.com/activeadmin-plugins/active_admin_import/blob/66dba6e5bfddc23996fb3dcef9f30865fa123a8f/lib/active_admin_import/importer.rb#L112

also there are specs on it , take a look at https://github.com/activeadmin-plugins/active_admin_import/blob/master/spec/import_spec.rb

**Comment by Fivell** [comment]
@rafaltrojanowski  consider add more details to your issue or spec that reproduce errors, for now closing as not reproducible
