### ISSUE TITLE
Howto add default additional data to csv parsed from file?

### ISSUE THREAD

**Issue by niksfirefly** [activeadmin-plugins/active_admin_import#17]
Howto add default additional data to csv parsed from file?
I can add additional headers in :before_batch_import
but how i can fill column with dynamic data
for example:
I got csv file with 2 headers: 
name, address
then in :before_batch_import i add header
client_id
so we got
name, address, client_id
and i want to fill additional column with data from
params[:client_id]

Is there a simple solution?

**Comment by amanders23** [comment]
Hi @Fivell, would you be able to give an example of this.  I'm using a custom template for the import and I want to add two drop downs, that will populate two id fields in the table that I'm importing into.  Thanks.

**Comment by amanders23** [comment]
@niksfirefly, were you able to get this working?  I'm trying to do the same thing...

**Comment by Fivell** [comment]
@amanders23 , do you have problems adding drop-downs or  saving data?

**Comment by amanders23** [comment]
Both.  I can a drop down like this, but it will not save the data to the table. 

<p class="active_admin_import_hint">
   <%= raw(@active_admin_import_model.hint) %> 
</p>
<%= semantic_form_for @active_admin_import_model, url: {action: :do_import}, html: {multipart: true} do |f| %>
    <%= f.inputs name: t("active_admin_import.details") do %>

    <%= select_tag 'catalog', 
      options_for_select(Catalog.all.collect{|catalog| [catalog.name, catalog.id, {:name=>catalog.name}] }, {:prompt => 'Catalog'})%>
        
        <%= f.input :file, as: :file %>
    <% end %>
   
    <%= f.actions do %>
        <%= f.action :submit, label: t("active_admin_import.import_btn"), button_html: {data: {disable_with: t("active_admin_import.import_btn_disabled")}} %>
    <% end %>
<% end %>

I can't add a drop down like this:

   <%=f.input :catalog_id, as: :select, :collection => Catal.pluck(:name, :id)%>

I get this error:
undefined method `catalog_id' for #<ActiveAdminImport::Model:0x007f91535b2660>


If I do the drop down the first way, should there be something in my active_admin_import to receive the catalog_id and place it in the table?

Here's what I have so far:

 active_admin_import :validate => true,
 :template => 'admin/course_import' ,
 headers_rewrites: { :'subjectarea_id' => :subjectarea_id, :'generaleducation_id' => :generaleducation_id,},
 before_batch_import: ->(importer) {
                subject_names = importer.values_at(:subjectarea_id)
                 # replacing subject area name with subject area id
                 subjects   = SubjectArea.where(name: subject_names).pluck(:name, :id)
                 options = Hash[*subjects.flatten] # #{"Jane" => 2, "John" => 1}
                 puts options
                 importer.batch_replace(:subjectarea_id, options)
                 
                  ge_names = importer.values_at(:generaleducation_id)
                  # replacing general education name with general education id
                  geneds  = GeneralEducation.where(name: ge_names).pluck(:name, :id)
                  options = Hash[*geneds.flatten] # #{"Jane" => 2, "John" => 1}
                  puts options
                  importer.batch_replace(:generaleducation_id, options)
                  
                  # catalog_names = params[:catalog_id]
 #              # replacing author name with author id
 #              catalogs  = Catalog.where(name: catalog_names).pluck(:name, :id)
 #              options = Hash[*catalogs.flatten] # #{"Jane" => 2, "John" => 1}
 #              puts options
 #              importer.batch_replace(:catalog_id, options)
 #
               },
 :template_object => ActiveAdminImport::Model.new(
 #:hint => "file will be imported with such header format: 'body','title','author'",
 :csv_headers => ["title", "code", "description", "credit", "start_date", "end_date", "local_course_id", "prefix", "section", "prerequisites", "corequisites", "books_url", "registration_url", "active", "level", "school_id", "subjectarea_id", "course_area", "generaleducation_id", "instructor", "course_method", "seats_available", "class_full"] 
 )

It works but the catalog_id field is not populate when the form is submitted.

Thanks!

**Comment by Fivell** [comment]
1) add needed attribute to ```ActiveAdminImport::Model```
```ruby
ActiveAdminImport::Model.new(
 #:hint => "file will be imported with such header format: 'body','title','author'",
: catalog_id => nil, #<<<this

 :csv_headers => ["title", "code", "description", "credit", "start_date", "end_date", "local_course_id", "prefix", "section", "prerequisites", "corequisites", "books_url", "registration_url", "active", "level", "school_id", "subjectarea_id", "course_area", "generaleducation_id", "instructor", "course_method", "seats_available", "class_full"] 
 )
```

**Comment by amanders23** [comment]
I added that, and it's still just a null entry into the table.  

here are my parameters that are being passed:

Parameters: {"utf8"=>"✓", "authenticity_token"=>"sh7ZY3vDoPfIdA6BNVqDZG9w/FFcxopZQK++9SitBcHeDkRAUGBclcLZK3BwUjrIFntlH7P7Ga1QvZZ+O6zxdg==", "catalog_id"=>"1", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007f915ec89be0 @tempfile=#<Tempfile:/var/folders/28/cs7w1cgs5bq7kx1dh_7j1kn00000gn/T/RackMultipart20150317-1413-1vn4yui.csv>, @original_filename="Winter 2014-15test.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"Winter 2014-15test.csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}

should catalog_id be outside of the active_admin_import_model?

I really appreciate your help with this!

**Comment by Fivell** [comment]
@amanders23 , not it shouldn't be outside, change form to make it model's attribute

**Comment by amanders23** [comment]
Sorry to be such a pain here, but I feel like I'm missing something...

Here's my form (catalog_id shows inside the active_admin_import_model)

<p class="active_admin_import_hint">
   <%= raw(@active_admin_import_model.hint) %> 
</p>
<%= semantic_form_for @active_admin_import_model, url: {action: :do_import}, html: {multipart: true} do |f| %>
    <%= f.inputs name: t("active_admin_import.details") do %>
            
              <%=f.input :catalog_id, as: :select, :collection => Catalog.pluck(:name, :id)%>  #this works now
            
               <%= f.input :file, as: :file %>
            <% end %>
    <%= f.actions do %>
        <%= f.action :submit, label: t("active_admin_import.import_btn"), button_html: {data: {disable_with: t("active_admin_import.import_btn_disabled")}} %>
    <% end %>
<% end %>

Here's my admin/courses.rb:


 active_admin_import :validate => true,
 :template => 'admin/course_import' ,
 headers_rewrites: { :'subjectarea_id' => :subjectarea_id, :'generaleducation_id' => :generaleducation_id,},
 before_batch_import: ->(importer) {

                
                subject_names = importer.values_at(:subjectarea_id)
                 # replacing subject area name with subject area id
                 subjects   = SubjectArea.where(name: subject_names).pluck(:name, :id)
                 options = Hash[*subjects.flatten] # #{"Jane" => 2, "John" => 1}
                 puts options
                 importer.batch_replace(:subjectarea_id, options)
                 
                  ge_names = importer.values_at(:generaleducation_id)
                  # replacing general education name with general education id
                  geneds  = GeneralEducation.where(name: ge_names).pluck(:name, :id)
                  options = Hash[*geneds.flatten] # #{"Jane" => 2, "John" => 1}
                  puts options
                  importer.batch_replace(:generaleducation_id, options)
                  

               },
 :template_object => ActiveAdminImport::Model.new(
 :catalog_id => nil,
 #:hint => "file will be imported with such header format: 'body','title','author'",
 :csv_headers => ["title", "code", "description", "credit", "start_date", "end_date", "local_course_id", "prefix", "section", "prerequisites", "corequisites", "books_url", "registration_url", "active", "level", "school_id", "subjectarea_id", "course_area", "generaleducation_id", "instructor", "course_method", "seats_available", "class_full"] 
 )


Here's the log: 
Started POST "/admin/courses/do_import" for 127.0.0.1 at 2015-03-17 13:09:29 -0400
Processing by Admin::CoursesController#do_import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"mBkil3iQzE6cpAX0tZETKhgGh0eq4npcXwxvouaWIUH0Cb+0UzMwLJYJIAXwmaqGYQ0eCUXf6ahPHkcp9ZfV9g==", "active_admin_import_model"=>{"catalog_id"=>"3", "file"=>#<ActionDispatch::Http::UploadedFile:0x007f8b8f7d9cc8 @tempfile=#<Tempfile:/var/folders/28/cs7w1cgs5bq7kx1dh_7j1kn00000gn/T/RackMultipart20150317-2408-rjwwfh.csv>, @original_filename="Winter 2014-15test.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"Winter 2014-15test.csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
   (0.5ms)  begin transaction
   (0.1ms)  SELECT "subject_areas"."name", "subject_areas"."id" FROM "subject_areas" WHERE "subject_areas"."name" IN ('subjectarea_id', 'Social Science')
{"Social Science"=>12}
   (0.2ms)  SELECT "general_educations"."name", "general_educations"."id" FROM "general_educations" WHERE "general_educations"."name" IN ('generaleducation_id', 'Social Sciences')
{"Social Sciences"=>9}
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`. (called from block in batch_import at /Users/Amelia/.rvm/gems/ruby-2.2.0@rails-devise/bundler/gems/active_admin_import-cb44dc235884/lib/active_admin_import/importer.rb:101)
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`. (called from block in batch_import at /Users/Amelia/.rvm/gems/ruby-2.2.0@rails-devise/bundler/gems/active_admin_import-cb44dc235884/lib/active_admin_import/importer.rb:101)
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`. (called from block in batch_import at /Users/Amelia/.rvm/gems/ruby-2.2.0@rails-devise/bundler/gems/active_admin_import-cb44dc235884/lib/active_admin_import/importer.rb:101)
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`. (called from block in batch_import at /Users/Amelia/.rvm/gems/ruby-2.2.0@rails-devise/bundler/gems/active_admin_import-cb44dc235884/lib/active_admin_import/importer.rb:101)
   (0.2ms)  select sqlite_version(*)
  Class Create Many Without Validations Or Callbacks (0.5ms)  INSERT INTO "courses" ("title","code","description","credit","start_date","end_date","local_course_id","prefix","section","prerequisites","corequisites","books_url","registration_url","active","level","school_id","subjectarea_id","course_area","generaleducation_id","instructor","course_method","seats_available","class_full","created_at","updated_at") VALUES ('title','code','description',0,NULL,NULL,'local_course_id','prefix','section','prerequisites','corequisites','books_url','registration_url','f','level',0,0,'course_area',0,'instructor','course_method',0,'f','2015-03-17 17:09:29.979404','2015-03-17 17:09:29.979431'),('General Psychology','101','An introduction to the science of psychology through the study of such topics as scientific inquiry, the brain, development, motivation, emotion, consciousness, learning, perception, memory, personality, and abnormality.',3,NULL,NULL,'14WI_ADI_PSY101_1','PSY','30047','<a href="https://banner.sunyacc.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in=201415&crn_in=30047" TARGET="_blank">Click here for additional information</a>',NULL,'https://securex.bncollege.com/webapp/wcs/stores/servlet/TBListView?cm_mmc=RI-_-8087-_-1-_-A&catalogId=10001&storeId=72236&termMapping=N&courseXml=','http://www.sunyacc.edu/academics/onlinelearning/enroll','t','Lower Level Undergraduate',2,12,'Psychology',9,'Dr. John Pennachio','Online',NULL,NULL,'2015-03-17 17:09:29.979404','2015-03-17 17:09:29.979431'),('General Psychology','101','An introduction to the science of psychology through the study of such topics as scientific inquiry, the brain, development, motivation, emotion, consciousness, learning, perception, memory, personality, and abnormality.',3,NULL,NULL,'14WI_ADI_PSY101_2','PSY','30057','<a href="https://banner.sunyacc.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in=201415&crn_in=30057" TARGET="_blank">Click here for additional information</a>',NULL,'https://securex.bncollege.com/webapp/wcs/stores/servlet/TBListView?cm_mmc=RI-_-8087-_-1-_-A&catalogId=10001&storeId=72236&termMapping=N&courseXml=','http://www.sunyacc.edu/academics/onlinelearning/enroll','t','Lower Level Undergraduate',2,12,'Psychology',9,'Dr. Joanne Malkani','Online',NULL,NULL,'2015-03-17 17:09:29.979404','2015-03-17 17:09:29.979431')
   (6.3ms)  commit transaction
Redirected to http://localhost:3000/admin/courses/import
Completed 302 Found in 42ms (ActiveRecord: 8.3ms)


It doesn't appear to be trying to insert catalog_id into the table.  If I add catalog_id to the csv_headers line, it tries to import it, but there is no value.
This is the error produced from that attempt: SQLite3::SQLException: 25 values for 26 columns: INSERT INTO "courses"

**Comment by Fivell** [comment]
@amanders23 , please format your message it is impossible to read

**Comment by amanders23** [comment]
Sorry about that, I'm new to using this editor.  I hope that is better looking.  I've pulled the log out of the comment above.  Let me know if you would like to see it.  I can't find a good way to clean it up.

**Comment by Fivell** [comment]
@amanders23 , I'll prepare spec example for your case for future needs

**Comment by amanders23** [comment]
That would be great! Thank you!

**Comment by Fivell** [comment]
```ruby
before_batch_import: ->(importer) {
  #your manipulation with data before import 
  #.....
  importer.csv_lines.map! { |row| row << importer.model.catalog_id}
  importer.headers.merge!({:'Catalog Id' => :catalog_id}) #this line needed if you're reading CSV headers from file, otherwise just put :catalog_id at the end of :csv_headers  declarative array 
}
```

**Comment by amanders23** [comment]
It works! Thanks you soooo much!
