### ISSUE TITLE
Handle a specific error on import 

### ISSUE THREAD

**Issue by linqueta** [activeadmin-plugins/active_admin_import#174]
Hey,

So, I want to run some filters before import the data using the option `before_batch_import`. One of this filter is to validate if a value of one column already exists in db. If not, I'll raise a specific error in my service class.

What do you think to pass as options what errors I wanna handle in this line https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L95 ?

If is it possible, I can send a pr to solve it.

**Comment by linqueta** [comment]
Giving an example:

My active admin file:
```ruby
active_admin_import validate: false,
                      template: 'variants/import',
                      template_object: ActiveAdminImport::Model.new(
                        csv_options: { col_sep: ';', row_sep: nil, quote_char: nil }
                      ),
                      before_batch_import: ->(importer) { Variant::ImportValidatorService.perform!(importer) }
```

My service class:
```ruby
# frozen_string_literal: true

class Variant
  module ImportValidatorService
    # TODO: Inherit StandardError
    # I asked the creators in the pr below to allow to pass a specific errors option,
    # but, NoMethodError is actually handled by the gem
    # https://github.com/activeadmin-plugins/active_admin_import/issues/174
    class SkuMissingError < NoMethodError; end

    class << self
      def perform!(_importer)
        raise SkuMissingError, I18n.t(:sku_missing, scope: %i[services import_validator])
      end
    end
  end
end
```

The result after import a csv file (in Portuguese): 
![image](https://user-images.githubusercontent.com/21321082/73386312-69cc6600-42ad-11ea-92f3-a3a821570267.png)

**Comment by Fivell** [comment]
@linqueta feel free to create PR , I think instead of overriding exception list maybe a good option can be to introduce new ActiveAdminImport
::Exception inherited from StandardError , so everyone can inherit it , and add this to https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L95

**Comment by linqueta** [comment]
> @linqueta feel free to create PR , I think instead of overriding exception list maybe a good option can be to introduce new ActiveAdminImport
> ::Exception inherited from StandardError , so everyone can inherit it , and add this to https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L95

Nice, I've agreed with it. After I finish my work today I'll do the pr. Thanks!
