### ISSUE TITLE
Ability to import serialized hash

### ISSUE THREAD

**Issue by prtk418** [activeadmin-plugins/active_admin_import#188]
For example if have a model as below:

```
class Model < ApplictionRecord
  serialize :data
  store_accessor :data, :key, :key1, :key2
end
```

In active admin dashboard i am able to create record by passing `:key`, `:key1`, `:key2` as parameters. Is there a way we can import this kind of data using this plugin?

**Comment by Fivell** [comment]
@prtk418 this plugin works on the top of  activerecord-import,  seems it is supported , reference https://github.com/zdennis/activerecord-import/pull/322 .



ME personally never tried to do it via active_admin_import, feel free to contribute if it doesn't work out of the box
