### ISSUE TITLE
ActiveModel::Errors#keys is deprecated and will be removed in Rails 6.2.

### ISSUE THREAD

**Issue by caljess599** [activeadmin-plugins/active_admin_import#194]
https://github.com/activeadmin-plugins/active_admin_import/blob/90e82de06cc6cfa2af10953a4c9597eac62e6fe6/lib/active_admin_import/import_result.rb#L36

`attribute_names` is now needed instead. 

See [active model's code] (https://github.com/rails/rails/blob/53410537594be0c0a528cff53dce433dd386cb6a/activemodel/lib/active_model/errors.rb#L273) for the specifics

**Comment by WvanLelyveld** [comment]
We are experiencing this error now, because of this:
```Error: undefined method `keys' for #<ActiveModel::Errors [#<ActiveModel::Error```

**Comment by WvanLelyveld** [comment]
Thanks!
