### ISSUE TITLE
Splitting an import field into two columns

### ISSUE THREAD

**Issue by amanders23** [activeadmin-plugins/active_admin_import#44]
Hello Again,  

This should be my last question. :)

I'm trying to import one column from the csv and split it into two in the database.  For example,  import code (101-VA)  insert into code (101) insert into section (VA)

```ruby
codes = importer.values_at(:code)
options_codes = codes.map {|codes|   {codes => codes.split('-').first}.flatten } 
options_sections = codes.map {|codes| {codes => codes.split('-').last}.flatten } 
options_codes = Hash[*options_codes.flatten]
options_sections = Hash[*options_sections.flatten]
importer.batch_replace(:'code', options_codes)
importer.csv_lines.map! { |row| row << options_sections}  #not entering one per row
importer.headers.merge!({:'section' => :section})
```

This is what I've been playing with, I have the code portion going into the code field, however I can't seem to get the section hash to enter one section per row.  Instead, the whole hash is going in a row.  Here is the section field from one of my records.

{"code"=>"code", "111-VA"=>"VA", "112-VA"=>"VA", "114-VA"=>"VA", "114-VB"=>"VB", "115-VA"=>"VA", "115-VB"=>"VB", "121-VA"=>"VA", "122-VB"=>"VB", "141-VA"=>"VA", "142-VA"=>"VA", "225-VB"=>"VB", "232-VB"=>"VB", "238-VA"=>"VA", "251-VA"=>"VA", "251-VB"=>"VB", "265-VB"=>"VB", "151-VA"=>"VA", "215-VB"=>"VB", "250-VA"=>"VA", "111-VB"=>"VB", "112-VB"=>"VB", "228-VB"=>"VB", "236-VA"=>"VA", "110-VB"=>"VB", "101-VA"=>"VA", "102-VB"=>"VB", "100-VA"=>"VA", "121-VB"=>"VB", "130-VA"=>"VA", "130-VB"=>"VB", "158-VB"=>"VB", "172-VB"=>"VB", "113-VB"=>"VB", "095-VB"=>"VB", "123-VB"=>"VB", "124-VA"=>"VA", "124-VB"=>"VB", "127-VA"=>"VA", "127-VB"=>"VB", "141-VB"=>"VB", "141-VS"=>"VS", "245-VB"=>"VB", "109-VA"=>"VA", "116-VA"=>"VA", "117-VA"=>"VA", "117-VB"=>"VB", "117-VS"=>"VS", "118-VA"=>"VA", "118-VB"=>"VB", "125-VA"=>"VA", "125-VB"=>"VB", "133-VS"=>"VS", "151-VB"=>"VB", "161-VA"=>"VA", "161-VB"=>"VB", "162-VA"=>"VA", "162-VB"=>"VB", "166-VS"=>"VS", "258-VS"=>"VS", "121-VS"=>"VS", "152-VA"=>"VA", "152-VB"=>"VB", "155-VA"=>"VA", "163-VB"=>"VB", "167-VB"=>"VB", "170-VA"=>"VA", "185-VA"=>"VA", "186-VB"=>"VB", "234-VA"=>"VA", "235-VS"=>"VS", "236-VS"=>"VS", "241-VA"=>"VA"}

Any thoughts on how to write one line at a time?

**Comment by Fivell** [comment]
@amanders23 , did you find solution ?

**Comment by amanders23** [comment]
No, I ended up splitting it in excel before the import.


<http://www.suny.edu/>[circle]<http://www.suny.edu/>



Amelia Manders
Senior Programmer/Analyst? ?
Open SUNY  - Web and Application Development Services
The State University of New York
State University Plaza - Albany, New York 12246
Tel: 518.320.1467   Fax: 518.320.1554
Be a part of Generation SUNY: Facebook<http://www.facebook.com/generationsuny> - Twitter<http://www.twitter.com/generationsuny>

________________________________
