### ISSUE TITLE
False flash message

### ISSUE THREAD

**Issue by abhishek77in** [activeadmin-plugins/active_admin_import#45]
Using (with bundle show) :
`active_admin_import-8d78ff9388ab` (latest)
`activeadmin-28e8a8f36640` (latest)
`rails-4.2.0`

I have a activerecord model name `Dog` which belongs to another model `Shelter`. When I try to import dogs to shelter, I get -
1. "Failed to import 82 dogs" - Which makes sense as my csv had `82 dog records`.
2. "Successfully imported 342 dogs" - Which makes *no sense* at all as `Shelter` only has 82 dogs which I tried to export and import. 342 sounds like a totally random number coming out from no where. Just to confirm the issue I tried the  import again but "Successfully imported 342 dogs" appears again.

![import___barkloudly_dashboard](https://cloud.githubusercontent.com/assets/749134/7029086/4c27f28a-dd78-11e4-9817-e981f0ab195d.png)

Also I am having trouble debugging the issue, since I was expecting a simple export - import of records to work smoothly.

**Comment by Fivell** [comment]
@abhishek77in , can you push app example and csv file to github, to reproduce issue . since this should not happen and there is spec which is succeed https://github.com/activeadmin-plugins/active_admin_import/blob/master/spec/import_spec.rb#L16

**Comment by abhishek77in** [comment]
Thanks @Fivell, makes sense unless I give you a reproducible issue it will be hard to tell what the problem is. Since this is a private repo it's hard to provide you with a example. Will close this issue for now and re-open once I have a reproducible issue.
