### ISSUE TITLE
undefined method `batch_replace' for #<ActiveAdminImport::Importer:0x007fc1ecd91fd8>

### ISSUE THREAD

**Issue by th3m4ri0** [activeadmin-plugins/active_admin_import#49]
I get this error for this code : 
```
before_batch_import: ->(importer) {
      importer.batch_replace(:bulk_def_lines, Hash["Y" => true, "N" => false])
    }
```

**Comment by Fivell** [comment]
@th3m4ri0 ,  your gemfile should contain unreleased version of gem

```gem "active_admin_import" , github: "activeadmin-plugins/active_admin_import"```

**Comment by th3m4ri0** [comment]
Thank you very much ! Works now :+1:
