### ISSUE TITLE
No import controls

### ISSUE THREAD

**Issue by hivemindunit** [activeadmin-plugins/active_admin_import#53]
Hi!

I just added this gem and enabled it for one of my ActiveAdmin objects like this:
```
ActiveAdmin.register Payment do
  active_admin_import
end
```
But now I can't find any controls that allow me to upload CSV. I expected it to appear on an index page for this object, is it correct?

**Comment by Fivell** [comment]
@hivemindunit , did you read wiki examples https://github.com/activeadmin-plugins/active_admin_import/wiki ?

**Comment by Fivell** [comment]
@hivemindunit , you should see import button in the action buttons sections.
https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L56

**Comment by hivemindunit** [comment]
@Fivell, thank you for a prompt reply!

Yes, I've tried also an option as described here: https://github.com/activeadmin-plugins/active_admin_import/wiki/allow-user-input-for--csv-options

with the same result (no import button on index page). There is neither no error messages nor import button sign in the page's source. What can go wrong and how I can debug that?

**Comment by Fivell** [comment]
@hivemindunit , if you use permission you should also allow import in pundit or cancan

**Comment by Fivell** [comment]
check this line https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L57

**Comment by hivemindunit** [comment]
@Fivell you are right, the problem was that current user didn't have required permissions.
I use CanCanCan gem and adding a permission into my ability class fixed the issue:
```
class Ability
  include CanCan::Ability
  def initialize(user)
    ...
    can :import, Payment
    ...
  end
end
```

**Comment by Fivell** [comment]
@hivemindunit , :+1:
