### ISSUE TITLE
Send email based on row imported

### ISSUE THREAD

**Issue by sunyatis** [activeadmin-plugins/active_admin_import#54]
Hi,

I'm trying to import several rows in a csv and send an email regarding any of them that have the "status" of  "pending".  On manual entry of a record, I have the email sending successfully.  I need to figure out how to send the email based on the contents of a row being imported.

sample file:
event_id   | event_date |	attendee | 	amount | trans_type | 	points_type |	institution_id |	status
------------ | ---------------- | ------------ | ---------------- | -------------- | -------------------- | ------------------- | ---------- 
Course 1: Assessment for Improvement of Teaching and Learning |	9/14/15	| |	225 | 	Debit	| CPD |	Adirondack Community College |	Pending 

Here is the method I can call  to pass the data to an email

PointsMailer.pending_email(row params).deliver_now

**Comment by Fivell** [comment]
@sunyatis , maybe after_batch_import hook can help. 
sort of 


```ruby

 ActiveAdmin.register Event  do
             active_admin_import validate: true,
              after_batch_import: ->(importer) {
                  pending_statuses = importer.values_at(:status).select {|s| s =='Pending'} 
                  PointsMailer.pending_email(pending_statuses).deliver_now
              }
         end

```

more examples https://github.com/activeadmin-plugins/active_admin_import/wiki
