### ISSUE TITLE
Semantic Errors

### ISSUE THREAD

**Issue by kyreeves** [activeadmin-plugins/active_admin_import#67]
Is there a way to display the errors of each model instance that fails to import?

**Comment by Fivell** [comment]
@kyreeves , try to add custom block , sort of

```ruby
 ActiveAdmin.register Post  do
    active_admin_import do 
        if  @importer.import_result.has_failed?
             flash[:notice] = 'Errors:'
             @importer.failed #collection of failed objects with validation errors, you can access them and retrieve errors
        end
    end
 end
```

**Comment by kyreeves** [comment]
@Fivell I got this error...

undefined method `import_result' for #<ActiveAdminImport::Importer:0x007fe51b4aa738>

**Comment by Fivell** [comment]
@kyreeves, try to use edge version from git , 
take a look https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/importer.rb#L30

**Comment by kyreeves** [comment]
@Fivell That worked! Thanks man!
