### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by asecondwill** [activeadmin-plugins/active_admin_import#68]
How can I go about importing associations? I've tried adding it to the CSV like this

````
 first_name,last_name,email,encrypted_password,industry
Joe,Blogs,user@example.com,12345678,gardening 
````

but i just get an "Missing column for value <industry> at index 4" error.  I guess because there isn't a Industry column on the user model.

**Comment by Fivell** [comment]
@asecondwill , is there industry_id column ? If yes take  a look to example https://github.com/activeadmin-plugins/active_admin_import/wiki/change-columns-on-the-fly-by-association

**Comment by asecondwill** [comment]
ok.  cool.  got it.  thanks fivell
