### ISSUE TITLE
Hook after_create doesn't run after importing

### ISSUE THREAD

**Issue by hivemindunit** [activeadmin-plugins/active_admin_import#70]
Hi @Fivell!

I came across a problem with running code for my imported objects.

I have a quite simple import setup:
```ruby
ActiveAdmin.register Payment do
    ...
    active_admin_import validate: true,
        timestamps: true,
        csv_options: { col_sep: ";", row_sep: nil, quote_char: nil }
    ...
end
```
I tried to use after_import hook but didn't figure it out how to obtain list of created records.
Is it possible to either enable after_create callback or run my code explicitly for newly created records?

**Comment by Fivell** [comment]
@hivemindunit , this gem uses ```activerecord-import``` under the hood .
Normal ActiveRecord callbacks will NOT be called when using activerecord-imports. This is because it is mass importing rows of data and doesn't necessarily have access to in-memory ActiveRecord objects.

**Comment by Fivell** [comment]
to access result of current import you can use this https://github.com/activeadmin-plugins/active_admin_import/wiki/before_batch_import-and-after_batch_import-options

**Comment by Fivell** [comment]
@hivemindunit , to emulate method after create try this snippet

```ruby
after_batch_import: proc{ |import|
             Post.where(id: importer.values_at('id')).each do |post|
                 post.my_method!
             end 
        
     }

```

**Comment by hivemindunit** [comment]
@Fivell, thank you! Id didn't work for me exactly as you suggested because I don't have ID column in my import file. I slightly modified it and it works just fine!

**Comment by Fivell** [comment]
@hivemindunit, yes any unique column or column combination can be used
