### ISSUE TITLE
Is it possible to add nested resource id on the fly?

### ISSUE THREAD

**Issue by lifecoderua** [activeadmin-plugins/active_admin_import#83]
I have a nested resource, like  `/libraries/15/commits` and want to import commits from css.

Is it possible to get the parent resource id and add it on the fly?

I could see the parent id in the Better Errors' dump as a `Request parameters > library_id` but can't figure how to catch it.

Thank you in advance.

**Comment by Fivell** [comment]
@lifecoderua ,  you can override template and add hidden input with library_id to make it model attribute https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/model.rb#L31
Template should be passed as option when declaring ```active_admin_import ``` for your resource

**Comment by Fivell** [comment]
Sort of this is possible

```ruby
before_filter only: [:do_import] do
    Thread.current['import.library_id'] =  params['library_id']
  end
  active_admin_import before_batch_import: ->(importer) do 
      importer.csv_lines.map{|line| line <<  Thread.current['import.library_id'] }
   end
```

**Comment by kxu1988** [comment]
"before_filter"  should change to "before_action" in Rails5.2
