### ISSUE TITLE
Question on how to use.

### ISSUE THREAD

**Issue by spurdow** [activeadmin-plugins/active_admin_import#87]
I kind of had a hard time implementing this on my end. I wish there was some example online.
What Im trying to do is , customizing what column to insert and before inserting I can customized some column values. 

Is this possible?

**Comment by Fivell** [comment]
@spurdow , there're examples https://github.com/activeadmin-plugins/active_admin_import/wiki

**Comment by Fivell** [comment]
https://github.com/activeadmin-plugins/active_admin_import/wiki/change-columns-on-the-fly-by-association  change column values hook example

**Comment by spurdow** [comment]
Ah what i mean is that.
Example:
I have a table named 'ALPHABET'
Column are A-Z
I only want to import then insert into B - C
is this possible?

Anyway Im really kind of having a hard time looking some simple example which I can import then insert. Is this library only import and let the programmer do the insert in after_import?

**Comment by Fivell** [comment]
@spurdow , this library is wrapper around activerecord-import gem. 
You can import in temporary table and implement custom logic using ```after_import``` hook https://github.com/activeadmin-plugins/active_admin_import/wiki/Importing-to-intermediate-table-with-insert-select-query-after-import-completion

**Comment by spurdow** [comment]
Oh i see, thank you (I never thought I would missed reading those important comments). Actually this is a really big help for me! 

thank you and God bless ^^
