### ISSUE TITLE
You can import only valid csv file

### ISSUE THREAD

**Issue by spurdow** [activeadmin-plugins/active_admin_import#88]
You can import only valid csv file, I dont get this error, is there a way that i could see the logs?

I have a csv file which I also have an importer table

this is my csv example but it doesnt get imported.

"name";"btype";"reg_no";"body_no";"plate_no";"capacity"
"BUS1";"1";"REGNO-xxx-xxxx";"BODY NO";"PLATE-XXX";"15"
"BUS2";"0";"REGNO-xxx-xxxx";"BODY NO";"LPATE-xxx";"15"
"BUS3";"1";"REGNO-xxx-xxxx";"BODY NO";"PLATE-XXX";"15"

and this is my import code
```ruby
ActiveAdmin.register Bus do
  active_admin_import validate: true,
                      csv_options: {col_sep: ";" },
                      resource_class: BusImport ,  # we import data into another resource
                      # before_import: proc{ .delete_all },
                      after_import: proc{
                        Bus.transaction do
                          Bus.connection.execute("INSERT INTO buses (name,btype,regno,body_no,plate_no,capacity) (SELECT name,btype,regno,body_no,plate_no,capacity FROM bus_imports)")
                        end
                      },
                      back: proc { config.namespace.resource_for(Bus).route_collection_path } # redirect to bus index
```

Is there something im missing?

**Comment by Fivell** [comment]
@spurdow, can you show your models BusImport and Bus

**Comment by spurdow** [comment]
its in here actually

https://github.com/jochun/lockout-ror/blob/master/db/migrate/20150704163947_create_bus.rb

the import bus is stripped down of bus
like below:

        t.string     :name
        t.integer    :btype
        t.text       :reg_no
        t.text       :body_no
        t.text       :plate_no
        t.integer    :capacity
        t.timestamps null: false

**Comment by Fivell** [comment]
@spurdow , what about BusImport table ?

**Comment by spurdow** [comment]
@Fivell  its just the same but without relationship only necessary fields for importing...

**Comment by spurdow** [comment]
@Fivell anyway, is there any way i could log the debug?

**Comment by Fivell** [comment]
@spurdow , application development.log or production.log depends on your env .  Here
https://github.com/activeadmin-plugins/active_admin_import/blob/87c584e257d7dad640557e5ca3ea8be86697f5da/lib/active_admin_import/dsl.rb#L81

**Comment by Fivell** [comment]
btw, did you try ```validate: false``` ?

**Comment by spurdow** [comment]
yeah tried both false and true... I dont fully understand what it really validates.

**Comment by spurdow** [comment]
is my csv file wrong? or is there some options im missing?

**Comment by Fivell** [comment]
@spurdow , show me your development logs for this request.

**Comment by Fivell** [comment]
@spurdow , your csv seems valid
```
 puts csv
"name";"btype";"reg_no";"body_no";"plate_no";"capacity"
"BUS1";"1";"REGNO-xxx-xxxx";"BODY NO";"PLATE-XXX";"15"
"BUS2";"0";"REGNO-xxx-xxxx";"BODY NO";"LPATE-xxx";"15"
"BUS3";"1";"REGNO-xxx-xxxx";"BODY NO";"PLATE-XXX";"15"
=> nil
irb(main):016:0> arr_of_arrs = CSV.parse(csv,col_sep: ';')
=> [["name", "btype", "reg_no", "body_no", "plate_no", "capacity"], ["BUS1", "1", "REGNO-xxx-xxxx", "BODY NO", "PLATE-XXX", "15"], ["BUS2", "0", "REGNO-xxx-xxxx", "BODY NO", "LPATE-xxx", "15"], ["BUS3", "1", "REGNO-xxx-xxxx", "BODY NO", "PLATE-XXX", "15"]]
```

**Comment by Fivell** [comment]
@spurdow, just noticed you're using 2.1.2
try master branch ```gem "active_admin_import" , github: "activeadmin-plugins/active_admin_import"```
give me a hint if you still have problems

**Comment by spurdow** [comment]
still the same :'(

**Comment by spurdow** [comment]
ill push my new commit today, i hope you will have the time to look it up.

**Comment by spurdow** [comment]
@Fivell how do I show the logs only for active admin import. I dont quiet get it.

**Comment by Fivell** [comment]
@spurdow , launch your app in development mode, make an import and capture new lines from development.log

**Comment by spurdow** [comment]
oh so its already default to log in development sorry, My bad. Okay ill post anything I deem wrong.

**Comment by spurdow** [comment]
Started POST "/admin/buses/do_import" for 127.0.0.1 at 2016-03-04 21:41:14 +0800
Processing by Admin::BusesController#do_import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"FVUKXS8oxknnBdBgoG6uN/YOC4y8KMisn3icnvbUvVVDmlqpro1UmXWm5X54gEtMSTnvVtvSx6pAH5PovlX2sg==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0000000de6a3e0 @tempfile=#<Tempfile:C:/Users/DAVIDL~1/AppData/Local/Temp/RackMultipart20160304-6960-sixmtq.csv>, @original_filename="buses (1).csv", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"buses (1).csv\"\r\nContent-Type: application/octet-stream\r\n">}, "commit"=>"Import"}
  AdminUser Load (1.0ms)  SELECT  `admin_users`.* FROM `admin_users` WHERE `admin_users`.`id` = 5  ORDER BY `admin_users`.`id` ASC LIMIT 1
--- !ruby/object:AdminUser
raw_attributes:
  encrypted_password: "$2a$10$/GTE3nFMoEUj31Q/sW8Qy.uiFNlfWqbAwTodn3Z/0aJoJrjzUE7va"
  id: 5
  email: ctccorominas_admin@gmail.com
  reset_password_token: 
  reset_password_sent_at: 
  remember_created_at: 
  sign_in_count: 6
  current_sign_in_at: &4 2016-03-04 13:07:06.000000000 Z
  last_sign_in_at: &5 2016-02-21 15:28:38.000000000 Z
  current_sign_in_ip: 127.0.0.1
  last_sign_in_ip: 127.0.0.1
  role: admin
  created_at: &6 2015-08-22 15:27:18.000000000 Z
  updated_at: &7 2016-03-04 13:07:06.000000000 Z
  company_id: 3
attributes: !ruby/object:ActiveRecord::AttributeSet
  attributes: !ruby/object:ActiveRecord::LazyAttributeHash
    types:
      id: &3 !ruby/object:ActiveRecord::Type::Integer
        precision: 
        scale: 
        limit: 4
        range: !ruby/range
          begin: -2147483648
          end: 2147483648
          excl: true
      email: &1 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString
        precision: 
        scale: 
        limit: 255
      encrypted_password: *1
      reset_password_token: *1
      reset_password_sent_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: &2 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlDateTime
          precision: 
          scale: 
          limit: 
      remember_created_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: *2
      sign_in_count: *3
      current_sign_in_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: *2
      last_sign_in_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: *2
      current_sign_in_ip: *1
      last_sign_in_ip: *1
      role: *1
      created_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: *2
      updated_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
        subtype: *2
      company_id: *3
    values:
      id: 5
      email: ctccorominas_admin@gmail.com
      encrypted_password: "$2a$10$/GTE3nFMoEUj31Q/sW8Qy.uiFNlfWqbAwTodn3Z/0aJoJrjzUE7va"
      reset_password_token: 
      reset_password_sent_at: 
      remember_created_at: 
      sign_in_count: 6
      current_sign_in_at: *4
      last_sign_in_at: *5
      current_sign_in_ip: 127.0.0.1
      last_sign_in_ip: 127.0.0.1
      role: admin
      created_at: *6
      updated_at: *7
      company_id: 3
    additional_types: {}
    materialized: true
    delegate_hash:
      encrypted_password: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: encrypted_password
        value_before_type_cast: "$2a$10$/GTE3nFMoEUj31Q/sW8Qy.uiFNlfWqbAwTodn3Z/0aJoJrjzUE7va"
        type: *1
        value: "$2a$10$/GTE3nFMoEUj31Q/sW8Qy.uiFNlfWqbAwTodn3Z/0aJoJrjzUE7va"
      id: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: id
        value_before_type_cast: 5
        type: *3
      email: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: email
        value_before_type_cast: ctccorominas_admin@gmail.com
        type: *1
      reset_password_token: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: reset_password_token
        value_before_type_cast: 
        type: *1
      reset_password_sent_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: reset_password_sent_at
        value_before_type_cast: 
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      remember_created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: remember_created_at
        value_before_type_cast: 
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      sign_in_count: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: sign_in_count
        value_before_type_cast: 6
        type: *3
      current_sign_in_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: current_sign_in_at
        value_before_type_cast: *4
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      last_sign_in_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: last_sign_in_at
        value_before_type_cast: *5
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      current_sign_in_ip: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: current_sign_in_ip
        value_before_type_cast: 127.0.0.1
        type: *1
      last_sign_in_ip: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: last_sign_in_ip
        value_before_type_cast: 127.0.0.1
        type: *1
      role: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: role
        value_before_type_cast: admin
        type: *1
      created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: created_at
        value_before_type_cast: *6
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      updated_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: updated_at
        value_before_type_cast: *7
        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
          subtype: *2
      company_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
        name: company_id
        value_before_type_cast: 3
        type: *3
new_record: false

  AdminUser Load (1.0ms)  SELECT  `admin_users`.* FROM `admin_users` WHERE `admin_users`.`email` = 'ctccorominas_admin@gmail.com'  ORDER BY `admin_users`.`id` ASC LIMIT 1
#<AdminUser:0x0000000d1e37c0>
  Subscription Exists (1.0ms)  SELECT  1 AS one FROM `subscriptions` WHERE `subscriptions`.`company_id` = 3 LIMIT 1
  Subscription Load (0.0ms)  SELECT  `subscriptions`.* FROM `subscriptions` WHERE `subscriptions`.`company_id` = 3  ORDER BY created_at DESC LIMIT 1
  Rendered C:/Ruby21-x64/lib/ruby/gems/2.1.0/bundler/gems/active_admin_import-8a7f300c94a4/app/views/admin/import.html.erb within layouts/active_admin (6.0ms)
Completed 200 OK in 543ms (Views: 528.0ms | ActiveRecord: 3.0ms)

**Comment by Fivell** [comment]
@spurdow , send "buses (1).csv" file to my email

**Comment by spurdow** [comment]
Ive sent u an email

**Comment by spurdow** [comment]
active_admin_import validate: true,
                      csv_options: {col_sep: ";" },
                      resource_class: BusImport ,  # we import data into another resource
                      # before_import: proc{ .delete_all },
                      after_import: proc{
                        Bus.transaction do
                          Bus.connection.execute("INSERT INTO buses (name,btype,regno,body_no,plate_no,capacity) (SELECT name,btype,regno,body_no,plate_no,capacity FROM bus_imports)")
                        end
                      },
                      back: proc { config.namespace.resource_for(Bus).route_collection_path } # redirect to post index

**Comment by spurdow** [comment]
Gemfile
```ruby

source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Active Admin
gem 'activeadmin', github: 'activeadmin'

gem 'devise' ,'~> 3.2'

gem "active_admin_import" , github: 'activeadmin-plugins/active_admin_import'

gem 'active_admin_datetimepicker'

# Use SCSS for stylesheets

gem "letter_opener"
gem 'gmaps4rails' , '~> 1.5.6'
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
gem 'draper', '~> 1.3'
gem 'coffee-script-source', '1.8.0'
# bundle update coffee-script-source
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem "just-datetime-picker"
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs wit
# h ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'cancan' ,'1.6.10'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'geocoder'



gem 'capistrano'


```

**Comment by Fivell** [comment]
@spurdow , I cloned your application and uploaded your file

**Comment by Fivell** [comment]
```
Started POST "/admin/buses/do_import" for ::1 at 2016-03-04 16:55:11 +0200
Processing by Admin::BusesController#do_import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"7lrDzsYroboNGoPec40aO82qlO5xuPxgy+WlM8mAIfjUcMU6rCpdIpLNiZ2Lhxp2Eh4ycIadaFpA8ZRsVYH3YQ==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007fb16543a9b8 @tempfile=#<Tempfile:/var/folders/g8/1r7jmb011_x7c20kd45dfb1h0000gn/T/RackMultipart20160304-98171-1c0v6rf.csv>, @original_filename="buses (1).csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"buses (1).csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}
  AdminUser Load (0.2ms)  SELECT  `admin_users`.* FROM `admin_users` WHERE `admin_users`.`id` = 3  ORDER BY `admin_users`.`id` ASC LIMIT 1
   (0.1ms)  BEGIN
   (0.3ms)  SHOW VARIABLES like 'max_allowed_packet';
  Class Create Many Without Validations Or Callbacks (0.5ms)  INSERT INTO `bus_imports` (`name`,`btype`,`reg_no`,`body_no`,`plate_no`,`capacity`,`created_at`,`updated_at`) VALUES ('BUS1',1,'REGNO-xxx-xxxx','BODY NO','PLATE-XXX',15,'2016-03-04 14:55:11','2016-03-04 14:55:11'),('BUS2',0,'REGNO-xxx-xxxx','BODY NO','LPATE-xxx',15,'2016-03-04 14:55:11','2016-03-04 14:55:11'),('BUS3',1,'REGNO-xxx-xxxx','BODY NO','PLATE-XXX',15,'2016-03-04 14:55:11','2016-03-04 14:55:11') ON DUPLICATE KEY UPDATE `bus_imports`.`updated_at`=VALUES(`updated_at`)
   (0.4ms)  COMMIT
   (0.1ms)  BEGIN
   (1.4ms)  INSERT INTO buses (name,btype,regno,body_no,plate_no,capacity) (SELECT name,btype,regno,body_no,plate_no,capacity FROM bus_imports)
Mysql2::Error: Unknown column 'regno' in 'field list': INSERT INTO buses (name,btype,regno,body_no,plate_no,capacity) (SELECT name,btype,regno,body_no,plate_no,capacity FROM bus_imports)
   (0.3ms)  ROLLBACK
Error: Mysql2::Error: Unknown column 'regno' in 'field list': INSERT INTO buses (name,btype,regno,body_no,plate_no,capacity) (SELECT name,btype,regno,body_no,plate_no,capacity FROM bus_imports)
```

**Comment by Fivell** [comment]
<img width="1413" alt="2016-03-04_1655" src="https://cloud.githubusercontent.com/assets/120269/13530551/84d81f30-e22a-11e5-8212-7e5d946fb775.png">

**Comment by spurdow** [comment]
aww how did you get it to error message like, I always get Invalid Csv

**Comment by spurdow** [comment]
Ive updated it , its wrong it should be reg_no

**Comment by spurdow** [comment]
![bus-csv](https://cloud.githubusercontent.com/assets/3696283/13530804/2f135f40-e25e-11e5-9ab6-06a8e150d66e.png)

I always get this error. What sdk are you using?

**Comment by Fivell** [comment]
@spurdow , looks like your browser dosn't sent correct mime type
Here is valdiation
https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/model.rb#L102

**Comment by spurdow** [comment]
Parameters: {"utf8"=>"✓", "authenticity_token"=>"zT7lA7DM5YrHN9fWVo9Q9HcuU3WAgPywljdsKjiMf9gzfe3V5Y4LsfnUxE4PBR3/99ZetdnE0DV0T+pnndKnOw==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0000000fa53250 @tempfile=#<Tempfile:C:/Users/DAVIDL~1/AppData/Local/Temp/RackMultipart20160304-6960-w8sf1v.csv>, @original_filename="buses (1).csv", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"buses (1).csv\"\r\nContent-Type: application/octet-stream\r\n">}, "commit"=>"Import"}

may i see your paramters?

**Comment by spurdow** [comment]
im using google chrome

**Comment by Fivell** [comment]
Parameters: {"utf8"=>"✓", "authenticity_token"=>"08bDVAuC3ijCAtLlTGvTN6n+OsBciLsRKHfdVNkrAjfp7MWgYYMisF3V2Ka0YdN6dkqcXqutLyujY+wLRSrUrg==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007fb165c62898 @tempfile=#<Tempfile:/var/folders/g8/1r7jmb011_x7c20kd45dfb1h0000gn/T/RackMultipart20160304-98171-vhb68h.csv>, @original_filename="buses (1).csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"buses (1).csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}

**Comment by spurdow** [comment]
aw i see it, content-type, Do i have to do something to fix this?

**Comment by Fivell** [comment]
@spurdow, this gem still doesn't detect mime type automatically, if this stops you from developing , just disable it and keep going by monkey-patching with your initializer

```
class ActiveAdminImport::Model
  def correct_content_type
     true
   end
end
```

**Comment by Fivell** [comment]
one more thing I noticed is that your database timestamps column are not nullable, 

To make import work use something like .


```ruby
active_admin_import validate: true,
                      csv_options: {col_sep: ";" },
                      timestamps: true,
                      resource_class: BusImport ,  # we import data into another resource
                      # before_import: proc{ .delete_all },
                      after_import: proc{
                        Bus.transaction do
                          Bus.connection.execute("INSERT INTO buses (created_at, updated_at, name,btype,reg_no,body_no,plate_no,capacity) (SELECT created_at, updated_at, name,btype,reg_no,body_no,plate_no,capacity FROM bus_imports)")
                        end
                      },
```

**Comment by spurdow** [comment]
wow thank you its working now.

**Comment by Fivell** [comment]
@spurdow , let me show how I would do this.

**Comment by spurdow** [comment]
```ruby 
after_import: proc{
                        Bus.transaction do
                          Bus.connection.execute("INSERT INTO buses (company_id, name,btype,reg_no,body_no,plate_no,capacity) (SELECT #{current_admin_user.company_id}, name,btype,reg_no,body_no,plate_no,capacity FROM bus_imports)")
                        end
                      },
```
is there any other way to do this? seems like that there is no current_admin_user

**Comment by Fivell** [comment]
```ruby

  before_filter only: [:do_import] do
    Thread.current['import.bus.company_id'] = current_admin_user.company_id
  end
  active_admin_import validate: false,
                      timestamps: true,
                      template_object: ActiveAdminImport::Model.new(
                          hint: "file will be imported with such header format: 'Bus Name','Registration ID','Body Number','Plate Number','Capacity'",
                          csv_headers: ["name" ,"btype", "reg_no", "body_no", "plate_no", "capacity", "company_id"],
                          csv_options: { col_sep: ";", quote_char: '"' }),
                          before_batch_import: ->(importer) { importer.csv_lines.map{|line| line <<  Thread.current['import.bus.company_id'] }}
```

**Comment by Fivell** [comment]
@spurdow , did it help ?

**Comment by spurdow** [comment]
wow , yes it works like a charm!

**Comment by Fivell** [comment]
@spurdow , good luck with your project

**Comment by spurdow** [comment]
@fivell ah thanks , its not really my project im seriously trying hard to learn this framework, cause i love the syntax and how the framework works.
