### ISSUE TITLE
Error: undefined method `*=' for #<*>

### ISSUE THREAD

**Issue by glen-mac** [activeadmin-plugins/active_admin_import#89]
Hey, I'm having an issues with this plugin and just cannot manage to fix it, even after reading all the past issues.

Here is my import.csv:
`"testname",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0`

My blend.rb (active admin):
```
ActiveAdmin.register Blend do

  #menu :if => proc{ current_admin.admin_type == 1}

  permit_params :Descriptor, :N, :Pav, :Pt, :K, :sS, :eS, :tS, :Ca, :Mg, :B, :Co, :Cu, :Fe, :Mn, :Mo, :Se, :Zn, :UREA, :SOA, :DAP, :MAP, :ZincStar, :MAPStar, :TSP, :SSP, :MOP, :SOP, :BS90, :HiMag, :B10, :B15, :Co21, :Cu25, :CuZn, :Fe25, :Mg55, :Mn32, :Mo13, :Mo39, :Se1, :Zn35, :AMS, :AMT, :UAT, :wSOA, :GUANO, :Agrotain, :Basis, :Flufol, :Orun, :Sweep

  #actions :all, :except => [:destroy]
  active_admin_import validate: true,
    csv_options: {},
    template: "admin/import",
    before_import: ->(importer){ Blend.delete_all },
    timestamps: true,
  template_object: ActiveAdminImport::Model.new(
    force_encoding: :auto,
    :csv_headers => ["Descriptor", "N", "Pav", "Pt", "K", "sS", "eS", "tS", "Ca", "Mg", "B", "Co", "Cu", "Fe", "Mn", "Mo", "Se", "Zn", "UREA", "SOA", "DAP", "MAP", "ZincStar", "MAPStar", "TSP", "SSP", "MOP", "SOP", "BS90", "HiMag", "B10", "B15", "Co21", "Cu25", "CuZn", "Fe25", "Mg55", "Mn32", "Mo13", "Mo39", "Se1", "Zn35", "AMS", "AMT", "UAT", "wSOA", "GUANO", "Agrotain", "Basis", "Flufol", "Orun", "Sweep"]
  )
```

and my schema.rb:
```
  create_table "blends", force: :cascade do |t|
    t.string   "Descriptor",               null: false
    t.decimal  "N",          default: 0.0
    t.decimal  "Pt",         default: 0.0
    t.decimal  "K",          default: 0.0
    t.decimal  "tS",         default: 0.0
    t.decimal  "Zn",         default: 0.0
    t.decimal  "Cu",         default: 0.0
    t.datetime "created_at",               null: false
    t.datetime "updated_at",               null: false
    t.decimal  "Pav",        default: 0.0
    t.decimal  "sS",         default: 0.0
    t.decimal  "eS",         default: 0.0
    t.decimal  "Ca",         default: 0.0
    t.decimal  "Mg",         default: 0.0
    t.decimal  "B",          default: 0.0
    t.decimal  "Co",         default: 0.0
    t.decimal  "Fe",         default: 0.0
    t.decimal  "Mn",         default: 0.0
    t.decimal  "Mo",         default: 0.0
    t.decimal  "Se",         default: 0.0
    t.decimal  "UREA",       default: 0.0
    t.decimal  "SOA",        default: 0.0
    t.decimal  "DAP",        default: 0.0
    t.decimal  "MAP",        default: 0.0
    t.decimal  "ZincStar",   default: 0.0
    t.decimal  "MAPStar",    default: 0.0
    t.decimal  "TSP",        default: 0.0
    t.decimal  "SSP",        default: 0.0
    t.decimal  "MOP",        default: 0.0
    t.decimal  "SOP",        default: 0.0
    t.decimal  "BS90",       default: 0.0
    t.decimal  "HiMag",      default: 0.0
    t.decimal  "B10",        default: 0.0
    t.decimal  "B15",        default: 0.0
    t.decimal  "Co21",       default: 0.0
    t.decimal  "Cu25",       default: 0.0
    t.decimal  "CuZn",       default: 0.0
    t.decimal  "Fe25",       default: 0.0
    t.decimal  "Mg55",       default: 0.0
    t.decimal  "Mn32",       default: 0.0
    t.decimal  "Mo13",       default: 0.0
    t.decimal  "Mo39",       default: 0.0
    t.decimal  "Se1",        default: 0.0
    t.decimal  "Zn35",       default: 0.0
    t.decimal  "AMS",        default: 0.0
    t.decimal  "AMT",        default: 0.0
    t.decimal  "UAT",        default: 0.0
    t.decimal  "wSOA",       default: 0.0
    t.decimal  "GUANO",      default: 0.0
    t.decimal  "Agrotain",   default: 0.0
    t.decimal  "Basis",      default: 0.0
    t.decimal  "Flufol",     default: 0.0
    t.decimal  "Orun",       default: 0.0
    t.decimal  "Sweep",      default: 0.0
  end

  add_index "blends", ["Descriptor"], name: "index_blends_on_Descriptor", unique: true, using: :btree
```

I just cannot get it to work. I have tried combinations of quotes and no quotes in the .csv, changed the lines around within blend.rb etc etc. I keep getting this error! Adding a new blend through 'New Blend' in active admin works fine.

Does anybody have any ideas?

**Comment by Fivell** [comment]
@glen-mac , please add backtrace of this error, not only message

**Comment by glen-mac** [comment]
@Fivell how do you recommend I do that - as the error appears just as a flash banner on the import screen - not usual rails error screen.

```
Started POST "/admin/blends/do_import" for ::1 at 2016-03-09 21:29:32 +1100
Processing by Admin::BlendsController#do_import as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"pe3+BP+xgt9KxiNhK7WvagpITSDCfQ+XR4zSSmT64Emz8tlpdHxhwM0gMZ+9HvWKmHOZHR+v8SY88VIp9S+Kgw==", "active_admin_import_model"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007fe79e394328 @tempfile=#<Tempfile:/var/folders/9g/bv4ryxsd26s3y_ngdvgljt880000gn/T/RackMultipart20160309-89314-1j6v1a2.csv>, @original_filename="iTool_blends copy.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"active_admin_import_model[file]\"; filename=\"iTool_blends copy.csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import"}
  Admin Load (0.2ms)  SELECT  "admins".* FROM "admins" WHERE "admins"."id" = $1  ORDER BY "admins"."id" ASC LIMIT 1  [["id", 1]]
  SQL (0.3ms)  DELETE FROM "blends"
   (0.5ms)  BEGIN
   (0.1ms)  ROLLBACK
Error: undefined method `descriptor=' for #<Blend:0x007fe794537e50>
Redirected to http://localhost:3000/admin/blends/import
Completed 302 Found in 38ms (ActiveRecord: 1.1ms)
```

**Comment by Fivell** [comment]
@glen-mac , pls also attach screen of flash message

**Comment by Fivell** [comment]
this may be reason  https://github.com/activeadmin-plugins/active_admin_import/blob/master/lib/active_admin_import/dsl.rb#L82

**Comment by glen-mac** [comment]
@Fivell 

<img width="1436" alt="screen shot 2016-03-09 at 9 35 48 pm" src="https://cloud.githubusercontent.com/assets/6212082/13632666/f277ac5a-e63e-11e5-8874-6e43ec5eea6d.png">

**Comment by Fivell** [comment]
@glen-mac , looks like out of the box camel-cased attributes are not supported .

**Comment by glen-mac** [comment]
@Fivell I see - any idea on an ETA for the fix, or should I just rename my attributes?

**Comment by Fivell** [comment]
@glen-mac , can you try  headers_rewrites options ? 
```
 headers_rewrites: { :'Descriptor' => :Descriptor ..... and so on },

```

**Comment by Fivell** [comment]
like here https://github.com/activeadmin-plugins/active_admin_import/blob/87c584e257d7dad640557e5ca3ea8be86697f5da/spec/import_spec.rb#L103

**Comment by Fivell** [comment]
or it may be sort of  
```
 headers_rewrites: { :'descriptor' => :Descriptor ..... and so on },
```

**Comment by Fivell** [comment]
@glen-mac , update me after your trying please

**Comment by glen-mac** [comment]
@Fivell it worked! Thanks so much for your help. The camel case of uppercase must be the issue..

My final (working) solution:
`  active_admin_import validate: true,
    before_import: ->(importer){ Blend.delete_all },
    timestamps: true,
    template_object: ActiveAdminImport::Model.new(
    #   force_encoding: :auto,
      :csv_headers => ["descriptor","n","pav","pt","k","ss","es","ts","ca","mg","b","co","cu","fe","mn","mo","se","zn","urea","soa","dap","map","zincstar","mapstar","tsp","ssp","mop","sop","bs90","himag","b10","b15","co21","cu25","cuzn","fe25","mg55","mn32","mo13","mo39","se1","zn35","ams","amt","uat","wsoa","guano","agrotain","basis","flufol","orun","sweep"]
    ),
    headers_rewrites: {:'descriptor' => :Descriptor, :'n' => :N, :'pav' => :Pav, :'pt' => :Pt, :'k' => :K, :'ss' => :sS, :'es' => :eS, :'ts' => :tS, :'ca' => :Ca, :'mg' => :Mg, :'b' => :B, :'co' => :Co, :'cu' => :Cu, :'fe' => :Fe, :'mn' => :Mn, :'mo' => :Mo, :'se' => :Se, :'zn' => :Zn, :'urea' => :UREA, :'soa' => :SOA, :'dap' => :DAP, :'map' => :MAP, :'zincstar' => :ZincStar, :'mapstar' => :MAPStar, :'tsp' => :TSP, :'ssp' => :SSP, :'mop' => :MOP, :'sop' => :SOP, :'bs90' => :BS90, :'himag' => :HiMag, :'b10' => :B10, :'b15' => :B15, :'co21' => :Co21, :'cu25' => :Cu25, :'cuzn' => :CuZn, :'fe25' => :Fe25, :'mg55' => :Mg55, :'mn32' => :Mn32, :'mo13' => :Mo13, :'mo39' => :Mo39, :'se1' => :Se1, :'zn35' => :Zn35, :'ams' => :AMS, :'amt' => :AMT, :'uat' => :UAT, :'wsoa' => :wSOA, :'guano' => :GUANO, :'agrotain' => :Agrotain, :'basis' => :Basis, :'flufol' => :Flufol, :'orun' => :Orun, :'sweep' => :Sweep}`

Note: I removed the headers from the .csv file and assigned them in the code itself - due to extra work required to process the .csv files.
