### ISSUE TITLE
Belongs to

### ISSUE THREAD

**Issue by ricardojudo** [activeadmin-plugins/active_admin_import#90]
Hello,
I have two active record based models, user and application where each user belongs to an application (every user must be associated with one application). I have configured the active admin artifacts on the following way.

```
ActiveAdmin.register User do
  belongs_to :application
  active_admin_import    before_batch_import: proc { |import|
    
  }
```

I can navigate through the applications and when I show the users, the . Besides, when I create a new single user this is associated automatically with the application do to the belongs_to sentence (so far, so good). 
However when I try to import several users through active_admin_import, I receive a message telling me that I can not insert a user with a blank application_id. In other words application is not set on users.
The question is.... Is there any configuration in order to honor the belongs_to association in the same way active_admin does?.
I was thinking a walk around were I pass the application_id from the request parameters to before_batch_import callaback, but I was not able to do that either.

**Comment by Fivell** [comment]
@ricardojudo , can you try this https://github.com/activeadmin-plugins/active_admin_import/issues/83#issuecomment-192328871 ?

**Comment by Fivell** [comment]
@ricardojudo , please update me if this is not working for you
