### ISSUE TITLE
CSV created with Excel on Mac Silently Fails

### ISSUE THREAD

**Issue by bpirtle** [activeadmin-plugins/active_admin_import#93]
There are no import errors, and it just appears to do nothing.

After a bunch of debug time reviewing the internals of the gem, I found that the Importer.import method cannot handle the format of the "default" CSV created by excel on mac. The failure occurs when the headers are properly discovered, but then the File.open block cannot find any lines. If you print out what it finds, it looks like the \r delimiter that Excel on mac CSV is not treated as a new line (I'm guessing it expects \r\n or similar), so the data all appears as a single line and thus it imports 0 rows without an error message.

The fix was to save in "CSV format for windows" inside excel, and everything works as it should.

I was able to see this on Rails 4.2, Ruby 2.1.3

**Comment by Fivell** [comment]
@bpirtle , thanks for information, can you share same file as here https://github.com/activeadmin-plugins/active_admin_import/blob/master/spec/fixtures/files/author.csv but with problem that you're describing.

**Comment by bpirtle** [comment]
![image](https://cloud.githubusercontent.com/assets/2916227/14067088/fea11914-f410-11e5-8aea-543ff15b0c83.png)

File is attached. Please let me know what you think/find.


[import_test_mac.zip](https://github.com/activeadmin-plugins/active_admin_import/files/191045/import_test_mac.zip)

**Comment by Fivell** [comment]
thanks @bpirtle , I'll  take a look

**Comment by Fivell** [comment]
@bpirtle . I can find next contents in this file using simple text  editor

> name,lastnam,birthday
> John,Doe,5/1/86
> ,,

**Comment by Fivell** [comment]
@bpirtle , I populated last line with valid data in this commit 51ef38763029027666878100e8ff30686ba0c83b, and looks like test were passed, so I can't confirm something doesn't work, fill free to reopen issue if I missed something

**Comment by bpirtle** [comment]
From my gemfile:

active_admin_import (2.1.2)
      activeadmin (>= 0.6.0)
      activerecord-import (~> 0.4, >= 0.4.1)
      rubyzip (~> 1.0, >= 1.0.0)

I just tried it and the mac csv version attached (denoted in the name) fails as described above while the windows version (denoted in the name) works properly.

There is certainly an issue, but you really need to test it live to reproduce as I have described. I'm not sure what kind of tests you ran to be unable to reproduce this.

[import_test_mac.zip](https://github.com/activeadmin-plugins/active_admin_import/files/219624/import_test_mac.zip)
[import_test_windows.csv.zip](https://github.com/activeadmin-plugins/active_admin_import/files/219625/import_test_windows.csv.zip)

**Comment by bpirtle** [comment]
Also, I'm not able to reopen this issue as far as I can tell

**Comment by Fivell** [comment]
@bpirtle , please recheck with  3.0.0.pre  and with master branch

**Comment by bpirtle** [comment]
Looks good in that version. Working properly with both files in 3.0.0.pre!
