### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by BrunoQuaresma** [activeadmin-plugins/active_admin_import#98]
How can i avoid the duplicate entry error when import a file?

**Comment by Fivell** [comment]
use on_duplicate_key_update option

**Comment by BrunoQuaresma** [comment]
I try but i dont understand how it works.

**Comment by Fivell** [comment]
@BrunoQuaresma ,  your problem is not clear for me

**Comment by BrunoQuaresma** [comment]
I solved my problem usinf

active_admin_import on_duplicate_key_update: [:updated_at]
